language: android
dist: trusty

notifications:
  email: false

jdk:
  - oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=10
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
    - EMU_NAME=test
    - EMU_API_LEVEL=23
    - EMU_ABI=armeabi-v7a
#    - EMU_ABI=x86

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMU_API_LEVEL
    - extra-android-support
    - sys-img-$EMU_ABI-google_apis-$EMU_API_LEVEL
  licenses:
    - 'android-sdk-license-.+'

before_install:
  - chmod +x gradlew
  #  https://github.com/travis-ci/travis-ci/issues/8874#issuecomment-350350607
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
  - yes | sdkmanager "platforms;android-$EMU_API_LEVEL"

script:
  - ./gradlew test

branches:
  only:
    - master